version: '3.7'

services:
  vscode:
    build:
      context: .
      dockerfile: Dockerfile-vscode
    ports:
      - "8081:8081"
    volumes:
      - ./input/fsh:/workspace/input/fsh

  apache:
    build:
      context: .
      dockerfile: Dockerfile-guia
    volumes:
      #- ./input/fsh:/var/www/html/input/fsh
      - ./input/fsh:/ig/input/fsh
    ports:
      - "8080:80"
      - "5000:5000"  # Expondo a porta do Flask no mesmo contêiner do Apache
    command: >
      /bin/bash -c "service apache2 start && python3 /ig/server.py"
    depends_on:
      - vscode

networks:
  default:
    driver: bridge
