# Usando uma imagem base com o VSCode
FROM codercom/code-server:latest

# Instala o VSCode e configurações adicionais se necessário
USER root
RUN apt-get update && apt-get install -y git curl

# Define o diretório de trabalho no container
WORKDIR /workspace

# Volumes compartilhados com o segundo container (input/fsh)
VOLUME /workspace/input/fsh

# Comando para inicializar o VSCode
CMD ["code-server", "--bind-addr", "0.0.0.0:8081", "/workspace"]
