FROM ubuntu

RUN apt update && \
    apt --yes install nodejs npm default-jre maven httpie ruby-full build-essential zlib1g-dev curl apache2 dos2unix git && \
    gem install jekyll bundler && \
    npm install -g --silent fsh-sushi@3.6.1 fhirpath@3.10.1

RUN git clone https://github.com/kyriosdata/ig \
    && cd ig \
    && chmod +x /ig/*.sh \
    && ./_updatePublisher.sh --yes \
    && ./_genonce.sh --yes \
    && cp -r /ig/output/. /var/www/html/

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]

